-- Flyway migration: knowledge_case + maintenance_process tables
-- for offline sync support, include version/updated_at/deleted_flag

CREATE TABLE IF NOT EXISTS knowledge_case (
    id                  BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    case_no             VARCHAR(64)     NOT NULL COMMENT '案例编号',
    title               VARCHAR(255)    NOT NULL COMMENT '案例标题',
    equipment_type      VARCHAR(128)    NULL COMMENT '设备类型',
    fault_type          VARCHAR(128)    NULL COMMENT '故障类型',
    fault_phenomenon    TEXT            NULL COMMENT '故障现象',
    fault_cause         TEXT            NULL COMMENT '故障原因',
    solution            TEXT            NULL COMMENT '处理方法',
    preventive_measures TEXT            NULL COMMENT '预防措施',
    work_type           VARCHAR(64)     NULL COMMENT '关联工单类型',
    enabled_flag        TINYINT         NOT NULL DEFAULT 1 COMMENT '是否启用',
    source_work_order_id BIGINT         NULL COMMENT '来源工单ID',
    attachment_ids      VARCHAR(500)    NULL COMMENT '附件ID列表，逗号分隔',
    local_id            VARCHAR(128)    NULL COMMENT '移动端本地ID',
    server_id           BIGINT          NULL COMMENT '服务端ID映射',
    version             INT             NOT NULL DEFAULT 1 COMMENT '同步版本号',
    sync_status         VARCHAR(32)     NOT NULL DEFAULT 'SYNCED' COMMENT '同步状态',
    device_id           VARCHAR(128)    NULL COMMENT '来源设备ID',
    operator_id         BIGINT          NULL COMMENT '最后操作人ID',
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_flag        TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    created_by          BIGINT          NULL COMMENT '创建人ID',
    updated_by          BIGINT          NULL COMMENT '更新人ID',
    remark              VARCHAR(500)    NULL COMMENT '备注',
    UNIQUE KEY uk_case_no (case_no),
    KEY idx_case_equipment (equipment_type),
    KEY idx_case_fault (fault_type),
    KEY idx_case_work_type (work_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故障案例表';

CREATE TABLE IF NOT EXISTS maintenance_process (
    id                  BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    process_code        VARCHAR(64)     NOT NULL COMMENT '工艺编号',
    process_name        VARCHAR(255)    NOT NULL COMMENT '工艺名称',
    equipment_type      VARCHAR(128)    NULL COMMENT '设备类型',
    process_type        VARCHAR(128)    NULL COMMENT '工艺类型',
    process_steps       TEXT            NULL COMMENT '工艺步骤',
    tools_required      TEXT            NULL COMMENT '所需工具',
    material_required   TEXT            NULL COMMENT '所需物料',
    safety_measures     TEXT            NULL COMMENT '安全措施',
    quality_standard    TEXT            NULL COMMENT '质量标准',
    duration_estimate   VARCHAR(64)     NULL COMMENT '预计工时',
    work_type           VARCHAR(64)     NULL COMMENT '关联工单类型',
    enabled_flag        TINYINT         NOT NULL DEFAULT 1 COMMENT '是否启用',
    local_id            VARCHAR(128)    NULL COMMENT '移动端本地ID',
    server_id           BIGINT          NULL COMMENT '服务端ID映射',
    version             INT             NOT NULL DEFAULT 1 COMMENT '同步版本号',
    sync_status         VARCHAR(32)     NOT NULL DEFAULT 'SYNCED' COMMENT '同步状态',
    device_id           VARCHAR(128)    NULL COMMENT '来源设备ID',
    operator_id         BIGINT          NULL COMMENT '最后操作人ID',
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_flag        TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    created_by          BIGINT          NULL COMMENT '创建人ID',
    updated_by          BIGINT          NULL COMMENT '更新人ID',
    remark              VARCHAR(500)    NULL COMMENT '备注',
    UNIQUE KEY uk_process_code (process_code),
    KEY idx_process_equipment (equipment_type),
    KEY idx_process_work_type (work_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维修工艺表';
